-- creating brands table
create table brands (brand_id int primary key,brand_name varchar (255));
-- making brand_id auto_incremental
ALTER TABLE brands MODIFY brand_id int AUTO_INCREMENT, AUTO_INCREMENT=1;


-- creating table categories
create table categories (category_id int primary key,category_title varchar (255));
-- making category_id auto_incremental
ALTER TABLE categories MODIFY category_id int AUTO_INCREMENT, AUTO_INCREMENT=1;


-- create table products
create table products (product_id int primary key,product_title varchar(255), product_description text, product_keyword varchar(255), category_id int references categories, brand_id int references brands, image1 varchar(255), price varchar(255), buylink text);
-- making product_id auto_incremental
ALTER TABLE products MODIFY product_id int AUTO_INCREMENT, AUTO_INCREMENT=1;




-- create table registration for storing admin information
create table registration (username varchar(255),password varchar(255));



-- adding the default categories
insert into categories(category_title) values ('Laptop'),('A/C'),('T.V'),('Refrigerators'),('Phone');

-- adding the default brands
insert into brands(brand_name) values ('HP'),('LG'),('Samsung'),('Sony'),('Asus'),('Redmi');



-- adding the defalut products and their details
insert into products(product_title,product_description,product_keyword,category_id,brand_id,image1,price,buylink) values 
("Poco F1","With the smartphone market buzzing with so many launches, Xiaomi has managed to make a mark by pricing the Poco F1 aggressively. It has all the elements of a Xiaomi phone: a powerful processor, MIUI, and a low price. In the company’s assault on the OnePlus 6 , many mid-range smartphones with far lower specifications have been taken down. The 6GB RAM/ 64GB storage variant of the Poco F1 is priced at Rs. 20,999, the 6GB RAM/ 128GB storage variant is priced at Rs. 23,999, and the 8GB RAM/ 256GB storage is priced at Rs. 28,999. The Armoured Edition, which we had for review, is priced at Rs. 29,999 and also has 8GB of RAM with 256GB of storage. Xiaomi has hit the ball right out of the park with the pricing of the Poco F1, and it’ll be interesting to see whether any manufacturer is interested in a price war.

The Qualcomm Snapdragon 845 is unheard of at these prices, but the Poco F1 also offers excellent battery life, something people have been asking for. The Armoured Edition uses Kevlar which feels different from the materials we already have in the market, though you may find the build quality of the other variants a bit underwhelming. All these factors make it an easy phone to recommend, though we would still like Xiaomi to tweak the camera on the Poco F1 for better low-light performance. Availability could be an issue with the Poco F1, as Xiaomi is once again relying on flash sales, and there’s sure to be enormous demand. If you do manage to get your hands on one of these phones, go for it because this is the best value you’ll get for your money.","phone,redmi,4g",5,6,'pocof1.jpg',24999,"https://www.flipkart.com/poco-f1-rosso-red-128-gb/p/itmf9c3ndhnupfek"),

("Samsung S23","The Samsung Galaxy S23 was announced on February 1, 2023, and went on sale on February 17 worldwide. Starting at $800, the Galaxy S23 is the same price as its predecessor, and the base model comes with 128GB of UFS 3.1 storage, with a 256GB model with UFS 4.0 storage costing $860. We've already seen some Galaxy S23 deals bring it down to $700 — and a Best Buy deal has brought it down to $600 — but trade-in deals for the baby S23 have been pretty lackluster outside of carriers. If you have an eligible unlimited plan and a relatively new phone, AT&T and Verizon will trade it to get you the S23 for free.
The Galaxy S23 is being sold by the three main U.S. carriers — AT&T, T-Mobile, and Verizon— as well as some MVNOs, though it’s been slower to arrive at ones not directly affiliated with a carrier. While the S23+ and S23 Ultra both have UWB support, the Galaxy S23 sticks to sub6 and mmWave. This review was conducted with an AT&T 256GB Lavender variant of the Galaxy S23 that I purchased myself. (Well, I traded in a Galaxy S20 for it, but you get the idea.)
5G testing was conducted in sub6 areas, as Orlando's AT&T mmWave coverage is quite limited, and tested on the vast Wi-Fi 6 mesh network at Walt Disney World's theme parks during both light and heavy crowd days. The S23 handles changing nodes in a larger mesh network pretty seamlessly, and 5G speeds were fine, but the S23 can cling to a weak or spotty Wi-Fi signal a hair long before kicking back to mobile data.","phone,samsung,5g",5,3,"samsungS23.jpg",74999,"https://www.flipkart.com/samsung-galaxy-s23-5g-cream-128-gb/p/itmc77ff94cdf044?pid=MOBGMFFX5XYE8MZN&lid=LSTMOBGMFFX5XYE8MZNRGKCA5&marketplace=FLIPKART&q=samsung+s23&store=tyy%2F4io&srno=s_1_2&otracker=search&otracker1=search&fm=organic&iid=4921601b-344a-4f7c-8b4b-0cb8354ffe8e.MOBGMFFX5XYE8MZN.SEARCH&ppt=pp&ppn=pp&ssid=eljhksaotc0000001685893657618&qH=1e144c4dcdb9bb43"),

("Sony Xperia 10 IV","Sony has updated its mid-ranger Xperia 10 for 2023. So what has changed coming from the Xperia 10 IV? Well, the display on Mark V has gotten slightly bigger and now measures 6.1 inches instead of 6.0. According to Sony, the panel itself is also 1.5x times brighter than before, which is great to see. They've also added front-facing stereo speakers. And there is the bigger 48MP main camera.
Unfortunately, that about covers the list of new additions to the Xperia 10 IV. Even though it is not that different from its predecessor, the Xperia 10 IV remains a rather special device with a unique Sony 'flavor' to it. We can't say whether that will be enough to guarantee its market success. What we can do, however, is delve into particulars and see what makes it tick.","phone,samsung,5g",5,4,"sony10V.jpg",46008,"https://phonesmart.co.in/product/sony-xperia-10-iv-xq-cc72-5g-black6gb-ram-128gb-storage/?srsltid=AR57-fAWGYPcowBeWBcE05PMAo4aFk37Km96jDupueIPWroiAjr9YyPZqZA"),

("Asus ROG Phone 7","The new ROG Phone has arrived a little bit earlier than its usual schedule this year, but you won't hear us complaining. Asus has simplified the lineup this time around, and there are just two devices - the ROG Phone 7 and the ROG Phone 7 Ultimate Edition. Both have essentially the same specs, sans for the ROG Vision display on the rear of the Ultimate and its AeroActive Portal for additional cooling, which is only present on the Ultimate.
We've already taken a look at the Ultimate model, and now it's time for the regular ROG Phone 7 to get the review treatment. You can thus expect many of the same features to make an appearance and a few references to the ROG Phone 7 Ultimate review.
Asus didn't change a whole lot with the new ROG Phone 7 generation. Most features are carried over from the ROG Phone 6, which is a good thing. After all, why change something that is clearly working?
Asus just went out to refine the phone in every way possible. The highlights include better computational performance, better speaker performance, and a brighter AMOLED display.
Other key features are still present as well, like the sturdy aluminum body and dual-glass design with Gorilla Glass Victus on the front and an ingress protection rating. The massive 6,000 mAh battery with 65W fast charging is also here, and so are the impressive controls and connectivity options, including the ROG AirTrigger inputs and the side port for accessories like the AeroActive cooler.","phone,asus,5g",5,5,"asusRog7.jpg",74999,"https://rog.asus.com/in/phones/rog-phone-7/"),

("HP Pavillion 14","The HP Pavilion 14 isn’t the type of sexy powerhouse that will change your life. However, it is a stable everyday performer that won’t blow your budget and will keep you pushing documents out at a good clip. It ticks off a lot of the boxes for students and workers participating in remote or in-person learning.
At ₹58,990, the Pavilion offers an attractive, affordable laptop with solid performance for day-to-day document pushing and content viewing. For what it offers at its price, this deserves a spot on our list of best HP laptops, along with our list of best laptops under ₹80,000.
With an Intel Core i5-1235U processor, 16GB of RAM, a 256GB SSD, and an Intel Iris Xe GPU, the Pavilion is capable of easily handling all your daily emails, YouTube breaks, documents, and school work. 
The Pavilion fared really well during our GeekBench 5.4 performance benchmark, scoring 7,072. It blew past the budget laptop average of 4,480 and owned this category. The Asus VivoBook 14 Flip (AMD Ryzen 5 5600H) placed second with 4,351, followed by the Lenovo Yoga (Intel Core i5-10210U) coming in next at 3,878, and the Flex 5 (11th Gen Intel Core i5-1135G7) rounding things out a 3,841.
Our review unit outpaced the budget laptop average (15:47) during the Handbrake video-editing test, taking 11 minutes and 55 seconds to transcode a 4K video to 1080p. However,  the VivoBook (11:37) took this category, but not by much. The Yoga C740 (20:42) and Flex 5 (25:30) brought up the back end during this benchmark.  
During the File Transfer test, the Pavilion took 2 minutes and 30 seconds to duplicate 25GB of mixed-media files for a transfer rate of 191.37 megabytes per second, placing it below the budget laptop average of 420.16MBps. The VivoBook  (512GB SSD) hit 563 MBps, the Flex 5 pumped out 565.9MBps, with the  Lenovo Yoga C740 (512GB SSD) being the speed demon of the group with its 848.2MBps transfer rate.
During our Sid Meier’s Civilization VI: Gathering Storm benchmark (1080p), the HP Pavilion mustered 27 fps, which outpaced the budget laptop average of 25 fps and exceeded the Flex 5 (16 fps) and Yoga C740 (8 fps).","laptop,hp",1,1,"hpPavillion14.jpg",58990,"https://www.amazon.in/HP-Pavilion-Anti-Glare-Graphics-14-dv1001TU/dp/B09MH5MLYP/ref=sr_1_1_sspa?adgrpid=64597729891&ext_vrnc=hi&hvadid=294104091963&hvdev=c&hvlocphy=9144864&hvnetw=g&hvqmt=b&hvrand=181249731998691596&hvtargid=kwd-298898393255&hydadcr=25655_1900986&keywords=hp+pavilion+14+i5&qid=1685894014&sr=8-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1"),

("Samsung Galaxy Book Flex","The Samsung Galaxy Book Flex is the company's latest attempt to stand out in a field it's had less-than-stellar success with: Windows PCs. But this 2-in-1 laptop offers a mix of strong performance with some unique features, to mostly successful results.
From its bright 15-inch screen to its strong performance and striking color, the Galaxy Book Flex is one of the best 2-in-1 laptops you can buy, one that brings Samsung back into the PC conversation. Even further, its nifty Qi-charging touchpad offers the kind of unique functionality we’d like to see other laptop makers use.
We also love the Galaxy Book Flex's fantastic endurance and solid performance, but there are some asterisks getting in the way. Specifically, its keyboard takes some getting used to, thanks to a questionably-placed fingerprint reader and shallow keys.
The 10th Gen Intel Core i7-1065G7 CPU and 12GB of RAM the Galaxy Book Flex allow for speedy multitasking. I saw no stutter when I split my screen between 12 Chrome tabs, including Google Docs and Giphy alongside a 1080p YouTube video (with Slack open in the background as well). 
On the Geekbench 4.3 general performance benchmark, the Galaxy Book Flex netted a 19,137 on the multi-core test. And while it falls under the 28,882 from the XPS 15 (Intel Core i9-9980HK processor and 32GB of RAM), that doesn't reflect poorly on the Galaxy Book Flex, as the XPS 15 model we tested packs a beefier CPU and more memory.The 512GB SSD in the Galaxy Book Flex duplicated 4.97 GB of files in 26.54 seconds, which is notably slower than the 10-second and 12-second transfer times from the XPS 15 (1TB SSD) and Spectre x360 (1TB SSD), respectively. 
On the Dirt 3 racing game, Galaxy Book Flex ran at 52 frames per second on Medium graphics at 1080p, but the Spectre x360 (Intel Core i7-8565U CPU, Nvidia GeForce MX150 GPU, 16GB of RAM) beat that with a rate of 118 fps.","laptop,samsung",1,3,"samsungBookFlex.jpg",107036,"https://www.samsung.com/us/computing/galaxy-books/galaxy-book-flex/galaxy-book-flex-13-3-qled-512gb-storage-s-pen-included-np930qcg-k01us/"),

("Asus ROG Zephyrus G14","The original Asus ROG Zephyrus G14 turned the laptop world on its head with an unheard-of performance-to-weight ratio for its day. Two years later, Asus is back with a redesigned ROG Zephyrus G14 that again challenges your notion of just how much performance you can jam into a tiny gaming laptop.
Much of this comes from its all-AMD design. Asus blends AMD’s ultra-efficient new Ryzen 9 6900HS processor and Radeon RX 6800S graphics into the revamped ROG Zephyrus G14. Because both CPU and GPU come from the same parent, they’re far more likely to shift power back-and-forth intelligently than, say, an Intel CPU and an Nvidia GPU.
Asus helps this partnership by using a vapor chamber cooling design rather than conventional heat pipes. Vapor chambers share a larger surface cooling area between the Radeon and Ryzen than a traditional heat pipe system, and benefit CPUs and GPUs that closely share power and cooling.
Besides the new internals, Asus moves from the wide and squat 16:9 aspect ratio panel to the new hotness with a 16:10 aspect ratio screen with a resolution of 2560×1600. The panel is rated at 500 nits, 120Hz and 100 percent DCI-P3 color space.
The real excitement of the newest ROG Zephyrus G14 is how it performs. We’ll kick that off with Cinbench R20, which is a 3D rendering benchmark based on Maxon’s Cinema4D engine. The more CPU cores you have, the better the performance. We actually tested the ROG Zephyrus G14 in its default “performance” setting as well as its “turbo” setting while plugged into the wall.
Although it can’t dethrone the much larger and much faster MSI GE76 Raider with its 12th-gen Core i9, the performance for the G14 is nonetheless impressive given its size and weight. For example, the 3.7 pound laptop (it’s even lighter without its nifty miniLED AniMe lid) outperforms the heavier and thicker ROG Strix G15 Advantage with its Ryzen 9 5900HX CPU.","laptop,asus",1,5,"asusRogG14.jpg",156990,"https://www.amazon.in/ASUS-Zephyrus-14-0-inch-35-56-GA402RJZ-L4136WS/dp/B0B93VJXYS/ref=asc_df_B0B93VJXYS/?tag=googleshopdes-21&linkCode=df0&hvadid=619830760757&hvpos=&hvnetw=g&hvrand=6818031067029016131&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9144864&hvtargid=pla-1920152505743&psc=1"),

("LG 1.5 Ton 5 Star Dual Inverter Split AC","In 2017, LG became the first brand to shift all of its models to the inverter compressor. Because of this step, soon the market of Inverter air conditioners spiked from 12% to staggering 60% with LG capturing the major chunk of it. Later on, LG launched the DualCool Inverter Compressor with latest ISEER ratings & the highest cooling score of 5 with Eco-friendly Refrigerant R32, 100% Copper, Gold Fin Condensor with Ocean Black Protection and 10-year warranty on compressor. At present, LG has the highest 38% market share* of inverter air conditioners.
Dual Inverter compressor of LG created a benchmark of energy efficiency for other brands and some brands are still catching up to it. There are only a few brands who sell a 5-star rated Inverter AC which is a clear proof of that. Call it Dual Inverter or DualCool Technology, it has Varied Speed Dual Rotor Compressor with the wider rotational frequency range. Dual Rotors inside the compressor function in tandem to ensure faster cooling and more efficiency as well as a considerable reduction in noise and vibration level.The biggest benefit you get out of it is more energy savings along with higher speed & better cooling range compared to conventional compressors. Technically this dual inverter compressor runs on variable speed to maintain the desired level of temperature resulting in assured savings in your electricity bills. Read this article to know more benefits of Dual Inverter Compressor.","A/C,LG",2,2,"lgAC.jpg",44490,"https://www.amazon.in/LG-Convertible-Anti-Virus-Protection-RS-Q19YNZE/dp/B0BQ3MXML8/ref=sr_1_3?keywords=LG+1.5+Ton+5+Star+Dual+Inverter+Split+AC&qid=1685894205&sr=8-3"),

("SAMSUNG Convertible 5-in-1 Cooling","Wi-Fi Enabled AI Auto Cooling Integrated with an AI Auto-cooling function, the Samsung AR18CYLZAWK 1.5-ton Split Inverter Air Conditioner analyses the usage patterns and room conditions to automatically optimise the different modes. In addition, it automatically sets the suitable mode as per your desired temperature, maintaining ideal conditions. SmartThings App With just a simple touch, you can remotely manage and keep an eye on this air conditioner using the SmartThings app. And, you can direct it with a voice assistant, such as Samsung Bixby, Amazon Alexa, or Google Assistant. Besides, it also recommends the ideal settings. So, you have complete control over this air conditioner anytime, anywhere Welcome Cooling Using the SmartThings App, this air conditioner's Welcome Cooling feature follows your phone's GPS to determine where you are. And, it uses your selected mode and settings to automatically set the room temperature at the desired level when you are within a predetermined distance. So, as soon as you arrive home on a hot summer afternoon, you can feel cool and comfortable. Convertible Inverter Modes Leveraging its five-step mode, this air conditioner modifies compressor operation between 40% and up to 120% to minimise energy consumption.
Additionally, you can use it when it's not too hot outside to chill more efficiently or simply conserve energy. As a result, you won't need to be concerned about significantly increased electricity bills. Improved Sleep Thanks to its Good Sleep mode, this air conditioner offers an excellent climate for peaceful sleep. And, it maintains a comfortable temperature, so you can fall asleep quickly, have a restful sleep, and wake up feeling refreshed. Auto-clean Function This air conditioner's Auto-clean function uses a three-step procedure to automatically dry the heat exchanger after it has been in use. Additionally, this eliminates moisture by circulating air for 10 to 30 minutes. This means that maintaining the cleanliness of this air conditioner's interior won't require any manual effort on your part. Enduring Performance Courtesy of the coated copper tubes in its heat exchanger, this air conditioner offers corrosion resistance, safeguarding it against harmful environmental factors, like dust and pollutants. This way, it contributes to improving dependability and durability while also reducing the need for frequent maintenance. Durafin Ultra Boasting Durafin Ultra, which includes anti-corrosive and hydrophilic layers, this air conditioner safeguards the heat exchanger from rust. R32 Refrigerant Built with an R32 refrigerant, this air conditioner helps save the ozone layer and has a low impact on global warming. This ensures that this air conditioner offers an eco-friendly operation.","A/C,samsung",2,3,"samsungAC.jpg",38900,"https://www.amazon.in/Samsung-Windfree-Technology-Convertible-AR18BY3ARWK/dp/B09SHXPXZ4/ref=sr_1_1?crid=5AQ11L2YHFW1&keywords=SAMSUNG+Convertible+5-in-1+Cooling&qid=1685894248&sprefix=samsung+convertible+5-in-1+cooling%2Caps%2C231&sr=8-1"),

("Samsung S95B OLED","The Samsung S95B OLED is a unique TV in Samsung's lineup. It's different from Samsung's QLED lineup, including the high-end Samsung QN95B, in that this TV uses a new QD-OLED panel. Along with the Sony A95K OLED, this new TV technology uses blue OLED panels with quantum dot color filters and is advertised to deliver much brighter colors than traditional white OLED displays, like the LG G2 OLED. Like other Samsung TVs, it uses Samsung's proprietary Tizen OS smart interface, which offers a large selection of apps and games. Samsung's main focus this year is on extra features, including support for Google Duo, which supports video calls with up to 32 people directly on your TV by connecting a supported webcam. There's also a large focus on gaming features, and it supports HDMI 2.1 bandwidth on all four ports and is FreeSync Premium certified. It's been replaced in 2023 by the Samsung S95C OLED, which offers similar picture quality but an updated design and an external Slim One Connect input box.
The Samsung S95B delivers a fantastic PC gaming experience, but it's not well-suited for productivity, as there are some serious deal-breakers. It has an exceptional viewing angle, so the sides of the screen remain accurate if you're sitting close to it. It also has low input lag and a nearly-instantaneous response time for a responsive, clear desktop experience. Unfortunately, even though it can accept and display a full chroma 4:4:4 signal, text isn't very clear due to the unusual subpixel layout, which can't be corrected with ClearType settings. It's also best enjoyed in a perfectly dark room, as the lack of a polarizer results in raised blacks if there's even a bit of ambient light.","TV,samsung",3,3,"samsungS95BTV.jpg",46490,"https://www.samsung.com/in/tvs/uhd-4k-tv/bu8500-43-inch-crystal-uhd-4k-smart-tv-ua43bu8570ulxl/"),

("LG G2 OLED","The LG G2 OLED is a high-end TV, and it's the successor to the LG G1 OLED. OLED TVs like the G2 are self-emissive, meaning unlike LCD panels found on other TVs, there's no backlight, which allows them to display a nearly-perfect contrast ratio in dark rooms, with deep inky blacks and no distracting blooming or halo-effect around bright objects. This TV has a unique design, and unlike most TVs, it doesn't even come with a stand, as it's designed to be mounted flush to your wall with the included slim wall mount.
Like other LG TVs, it uses the webOS smart interface, which has been slightly refreshed for 2022, adding user profiles among other minor changes. There's a huge focus on gaming features on the G2, including support for GeForce Now. The 'G' lineup isn't as popular as the rest of LG's lineup, as the unique design isn't cheap, but it's LG's highest-end 4k model in 2022, sitting above the more popular LG C2 OLED and below the 8k LG Z2 OLED.
The LG G2 OLED is a superb TV for most uses. Thanks to its nearly infinite contrast ratio it displays deep blacks with perfect uniformity, making it an exceptional choice for watching movies in a dark room. It's exceptionally bright for an OLED TV, making it a great choice for watching TV shows in a bright room. It also has an incredibly wide viewing angle, so it's a good choice for a wide seating arrangement. It's also an excellent choice for use as a PC monitor. Finally, it has an impressive selection of gaming features, and it delivers a superb gaming experience overall.","TV,LG",3,2,"lgG2Oled.jpg",149000,"https://www.lg.com/in/tvs/lg-oled55g2psa"),

("Redmi Smart TV x65","The Redmi X65 follows the same base design language that we have seen on Xiaomi's Mi branded smart TVs, i.e. basic yet functional. The overall look and feel and the material quality aren't going to blow your mind and could have been better. You can either mount the 65-inch TV on a wall or place it on a cabinet, provided that the TV unit is big enough to hold the two stands as they are positioned almost at the edges of this massive TV. The hard plastic table-top stand is bundled in the package, but Redmi hasn't included the wall-mount in the box. Why Redmi? I have a universal wall-mount that I use for 55-inch panels, and it worked with the Redmi X65 without any technical issues. If you don't have a universal mount and a table big enough to hold the TV, you must not think twice about buying the wall-mount from the market.
The 4K and HDR content look very immersive on the 65-inch panel. You must stream some episodes of Amazon Orignal's Tales from the loop (UHD, HDR), Netflix's Our Planet, Disney's Wanda Vision, etc. to witness the stunning visuals on the big screen TV. Not to forget the much-awaited Zack Snyder's Justice League that looked simply epic on the 65-inch TV even in the odd 4:3 aspect ratio. The HDR performance is good for the price but I have tested TVs doing slightly better than this in a similar price range. Sadly, most of these TVs are available in the 55-inch format. Xiaomi's very own Mi TV QLED is an excellent entry-level QLED TV but it is also available in 55-inch screen size. If you want a bigger panel in the same price bracket, you have to compromise a bit on the picture quality.
Xiaomi has an interesting offering with the Redmi TV X65 for Rs 64600. What it brings with it is support for eARC for home theatres, ALLM for gaming and support for a variety of HDR formats. While the overall picture quality is good for the price, HDR 10+ content still has some issues. SDR content playback is good. The HDMI 2.1 setting is switched off by default and getting to it involves jumping through some hoops when connecting the PS5. ","TV,redmi",3,6,"redmix65.jpg",57999,"https://www.amazon.in/Redmi-inches-Ultra-Android-L65M6-RA/dp/B08Y653FX4"),

("Samsung Double Door Refrigerator","The Samsung refrigerator boasts a sleek and stylish design that seamlessly blends with modern kitchen aesthetics. Its compact size with dimensions of 600 x 672 x 1635 mm and 56 kg weight allows it to fit into smaller spaces. The toughened glass shelves are not only durable but also easy to clean. Additionally, the LED light illuminates the interior, making it easy to locate items, even in low-light conditions.
The Samsung refrigerator incorporates Twin Cooling Plus technology which independently cools the freezer and refrigerator compartments. This technology helps maintain optimal humidity levels, preventing food items from getting dry or moist. The MoistFresh Zone is designed specifically for storing fruits and vegetables. The Powercool and Powerfreeze functions provide quick cooling and freezing, respectively. This ensures that your food items remain fresh and preserved. Further, the all-around cooling feature ensures even cooling throughout the refrigerator.
The Samsung  refrigerator is a frost-free refrigerator. With its powerful cooling capabilities, long-lasting freshness, and advanced features, this refrigerator is a suitable choice for families with three to four members.
Samsung Double Door Refrigerator is one of the popular refrigerators in this price range.","refrigerator,samsung",4,3,"samsungFride.jpg",41990,"https://www.amazon.in/Samsung-Convertible-Refrigerator-RT39C5532S8-HL/dp/B0BR3XL2VX/ref=sr_1_16?keywords=samsung+double+door+refrigerator&qid=1685894522&sr=8-16"),

("LG 3 Star Frost-Free Smart Inverter Wi-Fi Double Door Refrigerator","LG is a global corporation based in South Korea that manufactures electronics and home appliances. Founded in 1947, it initially produced cosmetics and plastic household products. The company expanded into electronics in 1958. Today, its product lineup includes refrigerators as well as washers and dryers, vacuums, air purifiers, TVs, laptops, earbuds, and more.
Five LG refrigerators made our Best Refrigerators of 2023 rating, including four French door models and one bottom-freezer refrigerator. LG also makes refrigerators in other styles including side-by-side, top-freezer, and single-door models, as well as in both standard-depth and counter-depth sizes. This review can help you decide if an LG fridge is a good fit for your kitchen.The adjustable temperature drawer, which LG calls the Full-Convert Drawer, sits between the fridge and the freezer. It has almost 3 cubic feet of storage space and five temperature settings – freeze, meat and seafood, deli items and snacks, cold drinks, and chilled wine – ranging from -7 to 41 degrees Fahrenheit. This pullout drawer could be great for those who entertain often, conveniently adding storage room for cakes, platters, or drinks.
This fridge also uses LG’s InstaView Door-in-Door technology. A tinted glass panel in the door allows you to see inside the refrigerator with two knocks, so you can browse what’s in the refrigerator without opening the door. This panel opens to an easily accessible compartment from which you can grab frequently used items while preventing cold air from escaping the rest of the refrigerator. Professional reviews note LG’s InstaView Door-in-Door feature sets it apart from other brands.","refrigerator,lg",4,2,"lgFridge.jpg",39990,"https://www.amazon.in/LG-Frost-Free-Refrigerator-%E2%80%8EGL-T342TESX-Convertible/dp/B0BSDQCTLQ/ref=sr_1_1?crid=1831JZH288V0D&keywords=LG+3+Star+Frost-Free+Smart+Inverter+Wi-Fi+Double+Door+Refrigerator&qid=1685894591&sprefix=lg+3+star+frost-free+smart+inverter+wi-fi+double+door+refrigerator%2Caps%2C226&sr=8-1");